name: Deploy Dokka to GitHub Pages

on:
  # Only trigger this when code is merged into main
  push:
    branches: ["main"]

# Grants the workflow permission to push to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Prevents multiple documentation deployments from running at the same time
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # We use macOS again to ensure the KMP project configures iOS targets successfully
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Generate Dokka HTML
        run: ./gradlew dokkaGenerateHtml --no-configuration-cache

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload Documentation Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/dokka/html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4